server:
  port: 9000
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  application:
    name: edge-service
  config:
    import: "optional:configserver:"
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
    gateway:
      routes:
      - id: catalog-route
        uri: ${CATALOG_SERVICE_URL:http://localhost:9001}/books
        predicates:
        - Path=/books/**
        filters:
        - name: CircuitBreaker
          args:
            name: catalogCircuitBreaker
            fallbackUri: forward:/catalog-fallback
      - id: order-route
        uri: ${ORDER_SERVICE_ROUTE:http://localhost:9002}/orders
        predicates:
        - Path=/orders/**
        filters:
        - name: CircuitBreaker
          args:
            name: orderCircuitBreaker
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s
      default-filters:
      - SaveSession
      - name: RequestRateLimiter
        args:
          redis-rate-limiter:
            replenishRate: 10
            burstCapacity: 20
            requestedTokens: 1
      - name: Retry
        args:
          retries: 3
          methods: GET
          series: SERVER_ERROR
          exceptions: java.io.IOException, java.util.concurrent.TimeoutException
          backoff:
            firstBackoff: 50ms
            maxBackoff: 500ms
            factor: 2
            basedOnPreviousValue: false
  redis:
    connect-timeout: 2s
    host: localhost
    port: 6379
    timeout: 1s
  session:
    store-type: redis
    timeout: 10m
    redis:
      namespace: polar:edge
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 20
        permitted-number-of-calls-in-half-open-state: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15000
  timelimiter:
    configs:
      default:
        timeout-duration: 5s
logging:
  level:
    '[io.github.resilience4j]': DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh

polar:
  greeting: Welcome to polar book catalog edge service!