apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
  labels:
    app: edge-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edge-service
  template:
    metadata:
      labels:
        app: edge-service
    spec:
      containers:
      - name: edge-service
        image: edge-service
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: [ "sh", "-c", "sleep 5"]
        ports:
        - containerPort: 9000
        env:
        - name: BPL_JVM_THREAD_COUNT
          value: "50"
        - name: BPL_DEBUG_ENABLED
          value: "true"
        - name: BPL_DEBUG_PORT
          value: "8001"
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-service:8888
        - name: edge_SERVICE_URL
          value: http://edge-service:9001
        - name: ORDER_SERVICE_ROUTE
          value: http://order-service:9002